name: "build-jdk-openj9"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: sophia-guo/build-jdk-openj9@v3
      id: buildOpenj9
      with: 
        version: 14
        usePersonalRepo: true
    - uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: configure_output
        path: ./**/config.log